[general]
import = ["~/.config/alacritty/current-theme.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
startup_mode = "Maximized"
option_as_alt = "Both"
resize_increments = true

[font]
normal.family = "JetBrainsMono Nerd Font Mono"
size = 14

[mouse]
hide_when_typing = true

[cursor]
style.shape = "Block"
style.blinking = "Never"
