[containers]
tz = "local"
env = ["BUILDAH_FORMAT=docker"]

[engine]
image_parallel_copies = 5
compose_warning_logs = false

[machine]
provider = "applehv"
rosetta = true
cpus = 6
memory = 8192
disk_size = 100
