#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

source "$CONFIG_DIR/settings.sh"

sketchybar --bar "${bar[@]}" --default "${default[@]}"

# --- Wake Recovery ---
# Fixes items not rendering after lid open (macOS timing issue)
sketchybar --add item wake_fix left \
	--set wake_fix drawing=off updates=off \
	script='sleep 1 && sketchybar --bar display=main display=all' \
	--subscribe wake_fix system_woke

# --- Left Side Items ---
source "$ITEM_DIR/disk.sh"
source "$ITEM_DIR/ram.sh"
source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/network_rates.sh"
source "$ITEM_DIR/media.sh"

# --- Right Side Items ---
source "$ITEM_DIR/datetime.sh"
source "$ITEM_DIR/input.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/network.sh"
source "$ITEM_DIR/sound.sh"
source "$ITEM_DIR/brew.sh"

sketchybar --hotload on
sketchybar --update
