# https://github.com/Homebrew/homebrew-bundle

# Taps
tap "homebrew/bundle"
tap "homebrew/command-not-found"
tap "homebrew/services"
tap "jorgelbg/tap"
tap "oven-sh/bun"

# Bottles
brew "bat"
brew "eza"
brew "fastfetch"
brew "fd"
brew "fzf"
brew "git"
brew "psutils"
brew "jq"
brew "jj"
brew "tree-sitter"
brew "neovim"
brew "ouch"
brew "poppler"
brew "ripgrep"
brew "rust"
brew "sevenzip"
brew "starship"
brew "podman"
brew "tmux"
brew "yazi"
brew "yq"
brew "zoxide"
brew "rich"


# Casks
cask "font-jetbrains-mono-nerd-font"
cask "font-symbols-only-nerd-font"
cask "alacritty"
cask "ghostty"
cask "kitty"

# Personal

tap "FelixKratz/formulae"

brew "openssl@3", link: false
brew "libpq"
brew "gnupg"
brew "pinentry"
brew "pinentry-mac"
brew "pinentry-touchid"
brew "jorgelbg/tap/pinentry-touchid"
brew "uv"
brew "tree"
brew "mkcert"
brew "postgresql@16"
brew "sketchybar"
brew "switchaudio-osx"
brew "lazygit"
brew "btop"
brew "bun"

cask "brave-browser"
cask "raycast"
cask "devtoys"
cask "font-sf-pro"
cask "sf-symbols"
cask "fbreader"
cask "obsidian"
cask "librewolf"
